spring.application.name=skillforge-api

spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge_db
spring.datasource.username=skillforge_user
spring.datasource.password=skillforge_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true