spring.application.name=skillforge-api

spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge_db
spring.datasource.username=skillforge_user
spring.datasource.password=skillforge_password
app.jwt.secret=0123456789012345678901234567890123456789012345678901234567890123
app.jwt.expiration-ms=86400000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true