CREATE TABLE learning_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100),
    description VARCHAR(100),
    difficulty VARCHAR(100),
    status VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE ,
    updated_at TIMESTAMP WITHOUT TIME ZONE ,
    created_by_id BIGINT REFERENCES users(id)

);

CREATE TABLE learning_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100),
    description VARCHAR(100),
    module_order INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE ,
    updated_at TIMESTAMP WITHOUT TIME ZONE ,
    learning_path_id BIGINT REFERENCES learning_paths(id)

);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100),
    description VARCHAR(100),
    task_order INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE ,
    updated_at TIMESTAMP WITHOUT TIME ZONE ,
    learning_module_id BIGINT REFERENCES learning_modules(id)
);